export default {

  FETCH_EXAM_LIST_START: 'FETCH_EXAM_LIST_START',
  FETCH_EXAM_LIST_SUCCESS: 'FETCH_EXAM_LIST_SUCCESS',
  FETCH_EXAM_LIST_FAIL: 'FETCH_EXAM_LIST_FAIL',


  FETCH_EXAM_CATEGORIES_START: 'FETCH_EXAM_CATEGORIES_START',
  FETCH_EXAM_CATEGORIES_SUCCESS: 'FETCH_EXAM_CATEGORIES_SUCCESS',
  FETCH_EXAM_CATEGORIES_FAIL: 'FETCH_EXAM_CATEGORIES_FAIL',

  };
