export default {
  FETCH_QUESTION_GROUP_START: 'FETCH_QUESTION_GROUP_START',
  FETCH_QUESTION_GROUP_SUCCESS: 'FETCH_QUESTION_GROUP_SUCCESS',
  FETCH_QUESTION_GROUP_FAIL: 'FETCH_QUESTION_GROUP_FAIL',


  FETCH_QUESTION_LIST_START: 'FETCH_QUESTION_LIST_START',
  FETCH_QUESTION_LIST_SUCCESS: 'FETCH_QUESTION_LIST_SUCCESS',
  FETCH_QUESTION_LIST_FAIL: 'FETCH_QUESTION_LIST_FAIL',


  FETCH_QUESTION_CATEGORIES_START: 'FETCH_QUESTION_CATEGORIES_START',
  FETCH_QUESTION_CATEGORIES_SUCCESS: 'FETCH_QUESTION_CATEGORIES_SUCCESS',
  FETCH_QUESTION_CATEGORIES_FAIL: 'FETCH_QUESTION_CATEGORIES_FAIL',




  FETCH_EXAM_LIST_START: 'FETCH_EXAM_LIST_START',
  FETCH_EXAM_LIST_SUCCESS: 'FETCH_EXAM_LIST_SUCCESS',
  FETCH_EXAM_LIST_FAIL: 'FETCH_EXAM_LIST_FAIL',



  FETCH_EXAM_GROUPS_START: 'FETCH_EXAM_GROUPS_START',
  FETCH_EXAM_GROUPS_SUCCESS: 'FETCH_EXAM_GROUPS_SUCCESS',
  FETCH_EXAM_GROUPS_FAIL: 'FETCH_EXAM_GROUPS_FAIL',
  };
